Jiya Sharma : 22311741

Assignment - 4

Apply appropriate ML algorithm on a dataset collected in a cosmetics shop showing details of
customers to predict customer response for special offer.
Create confusion matrix based on above data and find:

a) Accuracy

b) Precision

c) Recall

d) F-1 score

# Importing library

In [ ]:
import numpy as np
import pandas as pd

# Importing Dataset

In [ ]:
dataset = pd.read_csv('heart.csv')
X = dataset.iloc[: , :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [ ]:
print(y)

[0 0 0 ... 0 1 0]


# Splitting the Dataset into Training set and Testing Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state = 0 , test_size =0.2)

In [ ]:
print(X_train)

[[42.  1.  3. ...  2.  2.  2.]
 [66.  0.  2. ...  1.  1.  2.]
 [53.  1.  2. ...  2.  3.  2.]
 ...
 [65.  1.  3. ...  1.  1.  2.]
 [67.  1.  0. ...  1.  0.  2.]
 [60.  1.  2. ...  1.  0.  2.]]


In [ ]:
print(X_test)

[[44.  1.  2. ...  2.  0.  2.]
 [58.  0.  1. ...  2.  2.  2.]
 [63.  1.  0. ...  2.  2.  3.]
 ...
 [43.  0.  2. ...  1.  0.  2.]
 [66.  0.  0. ...  1.  2.  3.]
 [71.  0.  0. ...  1.  0.  2.]]


In [ ]:
print(y_train)

[1 1 1 1 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0
 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 0 0 1 1
 1 0 1 1 0 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 1 1 1 1
 0 1 0 1 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 0 0 0
 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 0 0 1 0 1 1 1 1 0 1 1 1
 1 0 0 1 0 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 1 1 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1
 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 1 1 1 0 1 0
 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0
 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1
 1 1 0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1
 0 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1
 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0
 1 0 1 0 1 0 0 0 0 1 1 0 

In [ ]:
print(y_test)

[1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0
 0 1 1 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0
 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 1 0 1 1
 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1
 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1
 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 1]


# Traing the Model on Training Set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train , y_train)

DecisionTreeClassifier()

# Testing the Model

In [ ]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
print(cm)

[[ 98   0]
 [  0 107]]


# Accuracy of the Model

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

1.0

# Precision of the Model

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test , y_pred)

1.0

# Recall score of the Model

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test , y_pred)

1.0

# F1 score of the Model

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test , y_pred)

1.0